-- Clear existing equipment types
DELETE FROM equipment_types;

-- Insert equipment types that match AddEquipment.tsx
INSERT INTO equipment_types (name, code, description) VALUES
('เครื่องคอมพิวเตอร์แม่ข่าย', 'SERVER', 'เครื่องแม่ข่าย'),
('เครื่องคอมพิวเตอร์', 'DESKTOP', 'เครื่องคอมพิวเตอร์ตั้งโต๊ะ'),
('จอแสดงภาพ', 'MONITOR', 'จอแสดงผลคอมพิวเตอร์'),
('เครื่องคอมพิวเตอร์โน้ตบุ๊ค', 'LAPTOP', 'เครื่องคอมพิวเตอร์แบบพกพา'),
('คอมพิวเตอร์แท็บเล็ต', 'TABLET', 'คอมพิวเตอร์แท็บเล็ต'),
('เครื่องสำรองไฟฟ้า', 'UPS', 'เครื่องสำรองไฟฟ้า'),
('สแกนเนอร์', 'SCANNER', 'เครื่องสแกนเอกสาร'),
('เครื่องพิมพ์', 'PRINTER', 'เครื่องพิมพ์เอกสาร'),
('ตู้สำหรับติดตั้งเครื่องแม่ข่ายชนิด Blade', 'BLADE_ENCLOSURE', 'ตู้สำหรับการติดตั้งเครื่องแม่ข่ายชนิด Blade (Enclosure/Chassis)'),
('แผงวงจรเครื่องแม่ข่ายชนิด Blade', 'BLADE_SERVER', 'แผงวงจรเครื่องคอมพิวเตอร์แม่ข่าย ชนิด Blade สำหรับตู้ Enclosure/Chassis'),
('อุปกรณ์จัดเก็บข้อมูลแบบภายนอก', 'EXTERNAL_STORAGE', 'อุปกรณ์สำหรับจัดเก็บข้อมูลแบบภายนอก (External Storage)'),
('อุปกรณ์จัดเก็บ Log File', 'LOG_STORAGE', 'อุปกรณ์จัดเก็บ Log File ระบบเครือข่าย'),
('อุปกรณ์ป้องกันเครือข่าย', 'FIREWALL', 'อุปกรณ์ป้องกันเครือข่าย (Next Generation Firewall)'),
('อุปกรณ์ป้องกันและตรวจจับการบุกรุก', 'IPS', 'อุปกรณ์ป้องกันและตรวจจับการบุกรุก (Intrusion Prevention System)'),
('อุปกรณ์ตรวจสอบช่องโหว่', 'VULNERABILITY_SCANNER', 'อุปกรณ์ตรวจสอบช่องโหว่ (Vulnerability Scanner)'),
('อุปกรณ์บริหารจัดการเหตุการณ์', 'SIEM', 'อุปกรณ์บริหารจัดการเหตุการณ์ (Security Information and Event Management)'),
('เครื่องมืออุปกรณ์เครือข่าย', 'NETWORK_TOOLS', 'เครื่องมืออุปกรณ์ใช้งานเครือข่าย'),
('อุปกรณ์กระจายสัญญาณเครือข่าย', 'NETWORK_SWITCH', 'อุปกรณ์กระจายสัญญาณเครือข่าย (Network Switch)'),
('อุปกรณ์ Access Point', 'ACCESS_POINT', 'อุปกรณ์ Access Point'),
('อุปกรณ์ขยายสัญญาณ', 'REPEATER', 'อุปกรณ์ขยายสัญญาณ (Repeater)'),
('อุปกรณ์แปลงสัญญาณ', 'MEDIA_CONVERTER', 'อุปกรณ์แปลงสัญญาณ (Media Converter)'),
('อุปกรณ์ Network Attached Storage', 'NAS', 'อุปกรณ์ Network Attached Storage (NAS)'),
('อุปกรณ์ทดสอบสายสัญญาณ', 'CABLE_TESTER', 'อุปกรณ์ทดสอบสายสัญญาณ'),
('อุปกรณ์วัดสัญญาณเครือข่าย', 'NETWORK_ANALYZER', 'อุปกรณ์วัดสัญญาณเครือข่าย'),
('โปรแกรมคอมพิวเตอร์', 'SOFTWARE', 'โปรแกรมคอมพิวเตอร์'),
('เครื่องปรับอากาศ', 'AIR_CONDITIONER', 'เครื่องปรับอากาศสำหรับห้องคอมพิวเตอร์'),
('ครุภัณฑ์สำนักงาน', 'OFFICE_EQUIPMENT', 'ครุภัณฑ์สำนักงานอื่นๆ'),
('ครุภัณฑ์วิทยาศาสตร์', 'SCIENCE_EQUIPMENT', 'ครุภัณฑ์วิทยาศาสตร์หรือการแพทย์'),
('ครุภัณฑ์โรงงาน', 'FACTORY_EQUIPMENT', 'ครุภัณฑ์โรงงาน'),
('ครุภัณฑ์ก่อสร้าง', 'CONSTRUCTION_EQUIPMENT', 'ครุภัณฑ์ก่อสร้าง'),
('ครุภัณฑ์การเกษตร', 'AGRICULTURE_EQUIPMENT', 'ครุภัณฑ์การเกษตร'),
('ยานพาหนะ', 'VEHICLE', 'ยานพาหนะ'),
('ครุภัณฑ์อื่นๆ', 'OTHER', 'ครุภัณฑ์อื่นๆ ที่ไม่จัดอยู่ในประเภทใดๆ ข้างต้น');