-- Insert new hospital departments
INSERT INTO public.departments (id, code, name, description, active, created_at, updated_at) VALUES
(gen_random_uuid(), 'MED', 'แพทย์', 'งานแพทย์และการรักษา', true, now(), now()),
(gen_random_uuid(), 'DENTAL', 'ฝ่ายทันตกรรม', 'ฝ่ายทันตกรรมและสุขอนามัยช่องปาก', true, now(), now()),
(gen_random_uuid(), 'PHARM', 'ฝ่ายเภสัชกรรม', 'ฝ่ายเภสัชกรรมและการจ่ายยา', true, now(), now()),
(gen_random_uuid(), 'MGMT', 'กลุ่มงานการจัดการ', 'กลุ่มงานการจัดการและบริหาร', true, now(), now()),
(gen_random_uuid(), 'STRATEGY', 'งานยุทธศาสตร์', 'งานยุทธศาสตร์และแผนงาน', true, now(), now()),
(gen_random_uuid(), 'INSURANCE', 'งานประกันสุขภาพ', 'งานประกันสุขภาพและสิทธิการรักษา', true, now(), now()),
(gen_random_uuid(), 'RECORD', 'งานเวชระเบียน', 'งานเวชระเบียนและสารสนเทศ', true, now(), now()),
(gen_random_uuid(), 'XRAY', 'งานเอ็กซเรย์', 'งานเอ็กซเรย์และรังสีวิทยา', true, now(), now()),
(gen_random_uuid(), 'LAB', 'งานชันสูตร', 'งานชันสูตรและห้องปฏิบัติการ', true, now(), now()),
(gen_random_uuid(), 'IPD', 'งานผู้ป่วยใน', 'งานผู้ป่วยในและการดูแลรักษา', true, now(), now()),
(gen_random_uuid(), 'IPD_MONK', 'งานผู้ป่วยใน (ตึกสงฆ์)', 'งานผู้ป่วยในสำหรับพระสงฆ์', true, now(), now()),
(gen_random_uuid(), 'OPD', 'งานผู้ป่วยนอก', 'งานผู้ป่วยนอกและคลินิก', true, now(), now()),
(gen_random_uuid(), 'NURSING', 'กลุ่มการพยาบาล', 'กลุ่มการพยาบาลและการดูแล', true, now(), now()),
(gen_random_uuid(), 'ER', 'งานอุบัติเหตุและฉุกเฉิน', 'งานอุบัติเหตุและฉุกเฉินแพทย์', true, now(), now()),
(gen_random_uuid(), 'TRANSPORT', 'งานเปล', 'งานเปลและขนส่งผู้ป่วย', true, now(), now()),
(gen_random_uuid(), 'NCD', 'งานโรคไม่ติดต่อ', 'งานโรคไม่ติดต่อและเรื้อรัง', true, now(), now()),
(gen_random_uuid(), 'PREVENT', 'งานเวชศาสตร์ฯ', 'งานเวชศาสตร์ป้องกัน', true, now(), now()),
(gen_random_uuid(), 'HEALTH_PROMO', 'งานส่งเสริมสุขภาพ', 'งานส่งเสริมสุขภาพและการป้องกัน', true, now(), now()),
(gen_random_uuid(), 'SUPPLY', 'งานซัพพลาย', 'งานซัพพลายและการจัดหา', true, now(), now()),
(gen_random_uuid(), 'SBP_ACU', 'รพ.สารภีบวรพัฒนา(ฝังเข็ม)', 'โรงพยาบาลสารภีบวรพัฒนา งานฝังเข็ม', true, now(), now()),
(gen_random_uuid(), 'SBP_PT', 'รพ.สารภีบวรพัฒนา(กายภาพบำบัด)', 'โรงพยาบาลสารภีบวรพัฒนา งานกายภาพบำบัด', true, now(), now()),
(gen_random_uuid(), 'SBP_IPD', 'รพ.สารภีบวรพัฒนา(ผู้ป่วยใน)', 'โรงพยาบาลสารภีบวรพัฒนา งานผู้ป่วยใน', true, now(), now()),
(gen_random_uuid(), 'SBP_MEETING', 'รพ.สารภีบวรพัฒนา(ห้องประชุม)', 'โรงพยาบาลสารภีบวรพัฒนา ห้องประชุม', true, now(), now()),
(gen_random_uuid(), 'SBP_OPD', 'รพ.สารภีบวรพัฒนา(ผู้ป่วยนอก)', 'โรงพยาบาลสารภีบวรพัฒนา งานผู้ป่วยนอก', true, now(), now()),
(gen_random_uuid(), 'SBP_TTM', 'รพ.สารภีบวรพัฒนา(แพทย์แผนไทย)', 'โรงพยาบาลสารภีบวรพัฒนา งานแพทย์แผนไทย', true, now(), now()),
(gen_random_uuid(), 'NUTRITION', 'งานโภชนาการ', 'งานโภชนาการและการกิน', true, now(), now()),
(gen_random_uuid(), 'TTM_SB', 'แพทย์แผนไทย(รพ.สารภี)', 'แพทย์แผนไทย โรงพยาบาลสารภี', true, now(), now()),
(gen_random_uuid(), 'TTM_KM', 'แพทย์แผนไทย(ศูนย์ขัวมุง)', 'แพทย์แผนไทย ศูนย์ขัวมุง', true, now(), now());