// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anfkslcoqeqmdcsumrnx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuZmtzbGNvcWVxbWRjc3Vtcm54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjM3ODUsImV4cCI6MjA3MzY5OTc4NX0.VGzaP1x7OjW_agrH2i7oVbucbCnbQUpuG6kCWZb3cJg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});